name: First Worlkflow
on: workflow_dispatch
jobs:
  First-job:
    runs-on: windows-latest
    steps:
      - name: print greeting
        runs: echo "Hello World!"
      - name: print goodbye
        runs: echo "Done-bye!"
